import TeacherList from '@/components/admin/teachers/teacher.list'


export const metadata = {
  title: 'Danh sách giảng viên',
  description: 'Generated by Gjngx',
}

function Teachers() {

  return (
    <div>
      <TeacherList/>
    </div>
  )
}

export default Teachers