import CourseList from '@/components/admin/courses/course.list'

export const metadata = {
  title: 'Danh sách môn học',
  description: 'Generated by Gjngx',
}

function Courses() {

  return (
    <div>
      <CourseList/>
    </div>
  )
}

export default Courses