import RoomList from '@/components/admin/rooms/room.list'


export const metadata = {
  title: 'Danh sách phòng học',
  description: 'Generated by Gjngx',
}

function Rooms() {

  return (
    <div>
      <RoomList/>
    </div>
  )
}

export default Rooms