import ClassList from '@/components/admin/aclasses/class.list'


export const metadata = {
  title: 'Danh sách lớp học',
  description: 'Generated by Gjngx',
}

function AClass() {

  return (
    <div>
      <ClassList/>
    </div>
  )
}

export default AClass